---
- include:
    install-immortal.yaml
  tags:
    immortal

- hosts: oprs

  name: Install oprspedia

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - ruby-erubis
        - ruby-nokogiri
        - ruby-sinatra
    repo:
      url:
        https://github.com/femnad/oprspedia.git

  roles:
    - clone
