---
- hosts:
    oprs
  name:
    Generate certificates

  vars:
    base_domain:
      oprspedia.org
    domains:
      - oprspedia.org
      - en.oprspedia.org
      - en.m.oprspedia.org
      - upload.oprspedia.org

  tasks:
    - name:
        Generate certificates
      command:
        certbot certonly --standalone -d {{ domains | join(",") }} -n
      become:
        yes

    - name:
        Locate certificate directory
      find:
        path:
          /etc/letsencrypt/live
        patterns:
          "{{ base_domain }}-*"
        file_type:
          directory
      become:
        yes
      register:
        certdirs

    - shell:
        cat fullchain.pem privkey.pem > /etc/haproxy/certs/{{ base_domain }}.pem
      args:
        chdir:
          "{{ certdirs.files | map(attribute='path') | list | last }}"
      become:
        yes
