---
- hosts:
    rhodium

  name: Install oprspedia

  vars:
    config_file:
      "{{ user_home }}/.oprspedia-config.yaml"

    deps:
      apt:
        - certbot
        - haproxy
        - ruby-erubis
        - ruby-sinatra
        - thin

    repo:
      url:
        https://github.com/femnad/oprspedia.git

    settings:
      port:
        127.0.0.1
      ip:
        4567

    user_service:
      name:
        oprspedia
      description:
        Oprspedia via Sinatra and Thin
      exec:
        /usr/bin/thin -R {{ source.path }}/src/oprspedia.ru -C {{ config_file }} start

  roles:
    - packages
    - clone
    - systemd_user_service

  post_tasks:
    - name:
        Fill in config file
      template:
        src:
          config.yaml.j2
        dest:

    - name:
        (Re)start Oprspedia service
      systemd:
        name:
          "{{ user_service.name }}"
        daemon_reload:
          yes
        state:
          restarted
        user:
          yes
      tags:
        service

- import_playbook:
    oprs_certificate.yaml
  tags:
    certbot, haproxy
