---
- include:
    install-immortal.yaml

- hosts: oprs

  vars:
    deps:
      apt:
        - ruby-erubis
        - ruby-nokogiri
        - ruby-sinatra
    repo:
      url:
        https://github.com/femnad/oprspedia.git

  roles:
    - clone
